version: '3'
services:
  tomcat:
    image: tomcat:9
    ports:
      - "8080:8080"
    volumes:
      - /etc/localtime:/etc/localtime
    container_name: tomcat
    networks:
      - tomcat-network
networks:
  tomcat-network:
    driver: bridge