version: '3'
services:
  zookeeper:
    image: zookeeper:latest
    ports:
      - "3888:3888"
      - "2888:2888"
      - "2181:2181"
    container_name: zookeeper
    networks:
      - zookeeper-network
networks:
  zookeeper-network:
    driver: bridge