version: '3'
services:
  openstreetmaps:
    image: homme/openstreetmap-tiles
    volumes:
      - /etc/localtime:/etc/localtime
    container_name: openstreetmaps
    networks:
      - openstreetmaps-network
networks:
  openstreetmaps-network:
    driver: bridge