version: '3'

volumes:
  mongodbdata1:

networks:
  mongodbnet1:

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
      - "28017:28017"
    volumes:
      - mongodbdata1:/data/db
    command: --smallfiles
    networks:
      - mongodbnet1
