version: '2'
services:
    tensorflow:
        image: gcr.io/tensorflow/tensorflow:0.11.0rc0
        ports:
            - "6006:6006"
            - "8888:8888"
        volumes:
            - /etc/localtime:/etc/localtime
            - ~/david/machine-learning/tensorflow:/opt/analytics/tensorflow
        container_name: tensorflow
