version: '3'
services:
  jenkins:
    image: jenkins:latest
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ~/data/jenkins:/var/jenkins_home
      - /private/var/run/docker.sock:/var/run/docker.sock
    container_name: jenkins
    networks:
      - jenkins-network
networks:
  jenkins-network:
    driver: bridge