version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/proxy.conf:/etc/nginx/conf.d/proxy.conf:ro
    depends_on:
      - jenkinsMaster
    networks:
      - jenkins-network
  jenkinsMaster:
    image: jenkins:latest
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ~/data/jenkins:/var/jenkins_home
      - /private/var/run/docker.sock:/var/run/docker.sock
    container_name: jenkins
    networks:
      - jenkins-network
networks:
  jenkins-network:
    driver: bridge