version: '3'
services:
  python:
    image: python:2
    container_name: python
    volumes:
      - ~/data/python:/usr/src/myapp
    working_dir: /usr/src/myapp
    networks:
      - python-network
  python3:
    image: python:latest
    container_name: python3
    volumes:
      - ~/data/python3:/usr/src/myapp
    working_dir: /usr/src/myapp
    networks:
      - python-network
networks:
  python-network:
    driver: bridge