version: '3'
services:
  mysql:
    image: mysql:latest
    ports:
      - "27017:27017"
    volumes:
      - ~/data/mysql:/datadb
      - /etc/localtime:/etc/localtime
    container_name: mongodb
    command: --smallfiles
    networks:
      - mysql-network
networks:
  mysql-network:
    driver: bridge