version: '2'
services:
    MySQL:
        image: mysql:5.7.11
        ports:
            - "27017:27017"
        volumes:
            - /usr/local/data/mongo:/datadb
            - /etc/localtime:/etc/localtime
        container_name: mongodb
        command: --smallfiles
