version: '3'

volumes:
  solrdata1:

networks:
  solrnet1:

services:
  solr:
    image: solr
    ports:
      - "8983:8983"
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - mycore
    volumes:
      - solrdata1:/opt/solr/server/solr/mycores
    depends_on:
      - zookeeper
    networks:
      - solrnet1
  zookeeper:
    image: zookeeper:3.4
    restart: always
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888
    networks:
      - solrnet1
