version: '3'
services:
  cassandra:
    image: cassandra:latest
    ports:
      - "7000:7000"
    volumes:
      - ~/data/cassandra:/var/lib/cassandra
      - /etc/localtime:/etc/localtime
    container_name: cassandra
    networks:
      - cassandra-network
networks:
  cassandra-network:
    driver: bridge