version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ~/data/redis:/data
      - /etc/localtime:/etc/localtime
    container_name: redis
    networks:
      - redis-network
networks:
  redis-network:
    driver: bridge